import uuid
from datetime import date as _date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Date, DateTime, ForeignKey, Numeric, SmallInteger, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.account import Account
    from app.models.transaction import Transaction


class LoanInstallment(Base):
    """One row of a loan's projected/actual amortization schedule (SAC or Price).

    The full schedule is (re)generated by `loan_service.create_or_replace_loan`
    whenever the loan's characteristics change. `try_reconcile_payment` marks
    rows `paid` by matching real transactions on the account against the
    nearest `projected` due date.
    """

    __tablename__ = "loan_installments"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("accounts.id", ondelete="CASCADE"), index=True
    )
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), index=True
    )
    installment_number: Mapped[int] = mapped_column(SmallInteger)
    due_date: Mapped[_date] = mapped_column(Date, index=True)
    amortization_amount: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2))
    interest_amount: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2))
    insurance_amount: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2), default=Decimal("0"))
    admin_fee_amount: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2), default=Decimal("0"))
    total_amount: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2))
    outstanding_balance_after: Mapped[Decimal] = mapped_column(Numeric(precision=15, scale=2))
    status: Mapped[str] = mapped_column(String(10), default="projected")  # projected, paid
    paid_date: Mapped[Optional[_date]] = mapped_column(Date, nullable=True)
    transaction_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("transactions.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    account: Mapped["Account"] = relationship()
    transaction: Mapped[Optional["Transaction"]] = relationship()
